### ISSUE TITLE
GMAIL: Browser not supported anymore

### ISSUE THREAD

**Issue by rayanaebi** [getferdi/recipes#608] opened 2021-08-13 08:48 UTC
**Describe the bug**
Gmail does not support Ferdi's browser version anymore and thus stops loading.

**To Reproduce**
1. Go to 'Services'
2. Click on '.Gmail'
3.  Try to log in
4. See error due to unsupported browser

**Expected behavior**
Gmail would just load and open using the latest version and bringing me to my inbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/47452243/129330658-c0a3816e-6bef-4b49-bdf1-dc5984790eba.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X

**Additional context**

**Comment by vraravam** [comment] 2021-08-13 08:51
Though this is the correct repo where this bug needs to be in, its a [duplicate of one](https://github.com/getferdi/ferdi/issues/1779) that has a possible workaround. Closing in favor of continuing the discussion in that one.

**Closed by vraravam** 2021-08-13 08:51 UTC
