### ISSUE TITLE
Notion SERVICE

### ISSUE THREAD

**Issue by Haasie** [getferdi/recipes#281] opened 2020-09-11 19:10 UTC
Name of the service: Notion
URL: https://www.notion.so/

Notion is a all in one workspace that provides good integrated collaboration.

For me it is esential since i make al mij notes/to-do's in it.

Can you please ad the service to ferdi?

**Comment by vantezzen** [comment] 2020-09-13 15:36
Duplicate of #134

**Closed by vantezzen** 2020-09-13 15:36 UTC
Labels: recipe request
