### ISSUE TITLE
Pipedrive

### ISSUE THREAD

**Issue by moralescarles** [getferdi/recipes#319] opened 2020-10-07 07:35 UTC
Name of the service (e.g. WhatsApp):  Pipedrive
URL of the service (e.g. whatsapp.com): www.pipedrive.com

GitHub URL to a recipe : 

Features you want implemented (optional):

-

**Comment by mhatvan** [comment] 2021-09-12 09:38
Closing as duplicate of https://github.com/getferdi/recipes/issues/376

**Closed by mhatvan** 2021-09-12 09:38 UTC
Labels: recipe request
