### ISSUE TITLE
[Recipe Request] Signal

### ISSUE THREAD

**Issue by ttrepper** [getferdi/recipes#200] opened 2020-06-13 12:32 UTC
Name of the service (e.g. WhatsApp): Signal
URL of the service (e.g. whatsapp.com): https://signal.org

Thanks a lot for all the brilliant work. :)
Thomas

**Comment by vantezzen** [comment] 2020-06-13 13:27
Duplicate of:
getferdi/ferdi#444
getferdi/ferdi#342
getferdi/recipes#185
getferdi/recipes#159
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.

**Closed by vantezzen** 2020-06-13 13:27 UTC
Labels: recipe request
