### ISSUE TITLE
[Recipe Request] LINE Messenger SERVICE

### ISSUE THREAD

**Issue by Druwy** [getferdi/recipes#255] opened 2020-08-11 15:56 UTC
LINE Messenger
https://line.me/en/

**Comment by Druwy** [comment] 2020-08-11 16:01
This is the main instant messaging app in South-East Asia and Japan where neither WhatsApp nor WeChat are commonly used.

**Comment by vantezzen** [comment] 2020-08-12 18:40
Thank you for requesting this. Unfortunately, LINE doesn't offer a web version of its messenger so we can't add it to Ferdi.

Duplicate of:
- #213
- #212 
- #33
- #28

**Closed by vantezzen** 2020-08-12 18:40 UTC
Labels: recipe request
