### ISSUE TITLE
Zenkit

### ISSUE THREAD

**Issue by ronak4444** [getferdi/recipes#347] opened 2020-10-29 06:37 UTC
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by mhatvan** [comment] 2021-09-12 09:45
Closing as duplicate of https://github.com/getferdi/recipes/issues/428

**Closed by mhatvan** 2021-09-12 09:45 UTC
Labels: recipe request
