### ISSUE TITLE
<SERVICE>

### ISSUE THREAD

**Issue by rolbru** [getferdi/recipes#414] opened 2021-01-14 09:24 UTC
Name of the service (e.g. WhatsApp): Signal (Messenger)
URL of the service (e.g. whatsapp.com): https://signal.org/de/

**Comment by S0obi** [comment] 2021-01-15 20:40
Duplicate with https://github.com/getferdi/recipes/issues/407

**Comment by rolbru** [comment] 2021-01-15 20:46
see https://github.com/getferdi/ferdi/issues/1155

**Comment by vraravam** [comment] 2021-05-27 16:34
Duplicate of #18

**Closed by vraravam** 2021-05-27 16:34 UTC
Labels: recipe request
