### ISSUE TITLE
Microsoft Todo

### ISSUE THREAD

**Issue by SalahAdDin** [getferdi/recipes#106] opened 2020-04-16 11:32 UTC
As you can know, Wunderlist was deprecated in favor to Microsoft TODO, and all users we had an account in that wonderful TODO service had to migrate to the new one.

Station has already this service in its list but Station itself consumes a lot of RAM memory, it is not elegant and useful like Ferdi, so, i also migrated to Ferdi; but i would like to use TODO in Ferdi too.

Thanks.

**Comment by vantezzen** [comment] 2020-04-16 12:23
Thank you for this suggestion. We will add Microsoft Todo in the future. Until then, you can already add this service by using the "Custom website" service.

**Comment by sampathBlam** [comment] 2020-04-17 15:28
Probably, a duplicate of #84 ?

**Comment by SalahAdDin** [comment] 2020-04-17 15:34
It is, should i close mine?

**Closed** 2020-04-17 15:48 UTC
Labels: duplicate
