### ISSUE TITLE
Custom Website not showing icon

### ISSUE THREAD

**Issue by JCKodel** [getferdi/recipes#422] opened 2021-01-20 21:41 UTC
**Describe the bug**
I've added a Custom Website pointing to AdMob (https://apps.admob.com/v2/home?pli=1) and used the admob logo (both SVG and PNG from https://cdn.worldvectorlogo.com/logos/google-admob.svg and  https://www.vhv.rs/dpng/d/574-5747918_google-admob-hd-png-download.png)

Dragging the files into the upload slot do nothing.

Selecting the file on the upload slot shows the logo in the Add Service window, but it doesn't show on the left bar:

![image](https://user-images.githubusercontent.com/379339/105244087-c2e07a00-5b4e-11eb-9472-cfc0a05c94a9.png)

**To Reproduce**
1. Add a new service
2. Choose Custom Website
3. Set URL to https://apps.admob.com/v2/home?pli=1
4. Upload some image

**Expected behavior**
The image should be saved and displayed (adjusted, if this is something related to image size or an error message in case SVG are not supported)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Ferdi 5.5.0.2116

**Comment by mhatvan** [comment] 2021-09-04 16:18
Cannot reproduce this, seems it was fixed by the PR linked above.

Custom .svg icon shows correctly on both macOS and Ubuntu, also after restarting Ferdi.

**Closed by mhatvan** 2021-09-04 16:18 UTC
