### ISSUE TITLE
[Recipe Request] MIRO

### ISSUE THREAD

**Issue by mlkplk** [getferdi/recipes#283] opened 2020-09-14 10:53 UTC
Name of the service (e.g. WhatsApp): Miro
URL of the service (e.g. whatsapp.com): https://miro.com/app/

GitHub URL to a recipe : none

Features you want implemented (optional):

- Notification support

**Comment by vantezzen** [comment] 2020-10-04 14:02
Duplicate of #280

**Closed by vantezzen** 2020-10-04 14:02 UTC
Labels: hacktoberfest, recipe request
