### ISSUE TITLE
<SERVICE> Signal

### ISSUE THREAD

**Issue by Greso665** [getferdi/recipes#407] opened 2021-01-10 19:29 UTC
Name of the service (e.g. WhatsApp): Signal
URL of the service (e.g. whatsapp.com): https://signal.org/

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment] 2021-05-27 16:32
Duplicate of #18

**Closed by vraravam** 2021-05-27 16:32 UTC
Labels: recipe request
