### ISSUE TITLE
[Defect] Google Drive connection seems to be hanging

### ISSUE THREAD

**Issue by sabine2020** [getferdi/recipes#73] opened 2020-03-23 18:24 UTC
I added Google Drive as new service and then tried to log into my account. After the verification by email, I can see that my Drive UI loads (upper right corner shows my account), but a popup appears saying "You are not signed in" and then the connection is hanging.

1. Add Google Drive as new Service
2. Log into Google account
3. Confirm the 2 step-verification
4. See error (attached screenshot)

**Expected behavior**
I should be able to work with my Google Drive account

**Screenshots**
see attached popup with disabled background (hanging...)
![you_are_not_signed_in](https://user-images.githubusercontent.com/62285981/77349757-ca22d580-6d3b-11ea-8e6c-933bdb10165b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.132 (64-bit)

**Comment by vantezzen** [comment] 2020-03-23 18:35
Thank you for reporting this bug.
Closing this as this is a duplicate of the bug report at https://github.com/getferdi/ferdi/issues/359

**Closed by vantezzen** 2020-03-23 18:35 UTC
