### ISSUE TITLE
[Recipe Request] SERVICE

### ISSUE THREAD

**Issue by MikeBlueberry** [getferdi/recipes#246] opened 2020-07-27 08:56 UTC
**Name of the service**: Yahoo mail
**URL of the service**: mail.yahoo.com
**Features you want implemented**: Be able to access Yahoo email in Ferdi.

**Comment by MikeBlueberry** [comment] 2020-07-27 08:57
Thank you for looking.

**Comment by vantezzen** [comment] 2020-07-28 18:31
Duplicate of #178

**Closed by vantezzen** 2020-07-28 18:31 UTC
Labels: recipe request
