### ISSUE TITLE
Custom icon doesn't work

### ISSUE THREAD

**Issue by sinattieng** [getferdi/recipes#467] opened 2021-04-12 11:23 UTC
**Describe the bug**

The functionality "custom icons" not work, indeed after having added one, the preview works but the ui doesn't show it (black box instend of it)

**To Reproduce**
Add a custom icon.
Check the lateral menu.

**Comment by dpanter** [comment] 2021-04-19 16:18
Custom icons seem to work for me on Debian sid, using transparent PNG files.

**Comment by vraravam** [comment] 2021-05-27 16:26
Unable to reproduce without more information on what OS, what version of Ferdi, the specific custom icon that you are using, etc. Closing the issue for now.

**Closed by vraravam** 2021-05-27 16:26 UTC
