### ISSUE TITLE
Please support the signal messenger

### ISSUE THREAD

**Issue by tomAufGithub** [getferdi/recipes#22] opened 2020-01-07 08:42 UTC
**Is your feature request related to a problem? Please describe.**
I miss the support of the signal messenger.

**Describe the solution you'd like**
Exactly as Whatsapp is supported i would like to have support for signal.

**Comment by vantezzen** [comment] 2020-01-07 09:19
Duplicate of #18.
Signal currently doesn't offer a web version of their messenger (only a desktop version). Due to this we can't add Signal to Ferdi.

**Closed** 2020-01-07 09:19 UTC
