### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by skinnard** [getferdi/recipes#360] opened 2020-11-11 15:07 UTC
Name of the service (e.g. WhatsApp): YouTube
URL of the service (e.g. whatsapp.com): https://youtube.com

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by mhatvan** [comment] 2021-09-12 09:36
Closing as duplicate of https://github.com/getferdi/recipes/issues/403

**Closed by mhatvan** 2021-09-12 09:37 UTC
Labels: recipe request
