### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by netanel0909** [getferdi/recipes#391] opened 2020-12-16 09:38 UTC
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vantezzen** [comment] 2020-12-16 16:54
Duplicate of #205. Unfortunately, we can't add Spotify as the service requires a Widevine DRM Certificate which is only given to large corporations like Google or Microsoft.

**Closed** 2020-12-19 12:54 UTC
Labels: recipe request

**Comment by netanel0909** [comment] 2020-12-19 12:59
Thanks anyway 😉
