### ISSUE TITLE
Gmail open link problem

### ISSUE THREAD

**Issue by MauricioAedo** [getferdi/recipes#193] opened 2020-06-01 15:44 UTC
**Describe the bug**
I can't open links in Gmail.

**To Reproduce**
1. Go to 'Gmail'
2. Open an email
2. Click on 'a external link'
3. See error

**Expected behavior**
I expected that link open in my default navigator

**Screenshots**
![image](https://user-images.githubusercontent.com/20685077/83426267-e3f82d00-a3fc-11ea-9aae-384143c32fbc.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Google Chrome
 - 83

**Additional context**
In Station that problem doesn't exists.

**Comment by vantezzen** [comment] 2020-06-02 06:00
Duplicate of getferdi/ferdi#321

**Closed by vantezzen** 2020-06-02 06:00 UTC
