### ISSUE TITLE
[Recipe Request] SERVICE

### ISSUE THREAD

**Issue by scoutfree** [getferdi/recipes#250] opened 2020-07-31 17:09 UTC
Name of the service (e.g. WhatsApp):  Yahoo Mail
URL of the service (e.g. whatsapp.com): mail.yahoo.com

GitHub URL to a recipe : https://github.com/...

I couldn't find any franz recipe for this

Features you want implemented (optional):

For me it's enough to be able to check email, thanks!

-

**Comment by vantezzen** [comment] 2020-08-01 08:13
Duplicate of #178

**Closed by vantezzen** 2020-08-01 08:13 UTC
Labels: recipe request
