### ISSUE TITLE
Bip <https://web.bip.com/chat>

### ISSUE THREAD

**Issue by bulutbey15** [getferdi/recipes#462] opened 2021-03-31 11:02 UTC
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment] 2021-06-19 12:07
Duplicate of #461

**Closed by vraravam** 2021-06-19 12:07 UTC
Labels: recipe request
