### ISSUE TITLE
Signal service

### ISSUE THREAD

**Issue by DamienCasoni** [getferdi/recipes#481] opened 2021-04-30 20:04 UTC
Name of the service (e.g. WhatsApp): Signal
URL of the service (e.g. whatsapp.com): https://signal.org/

GitHub URL to a recipe : https://github.com/lukasholzer/signal-franz-plugin

Features you want implemented (optional):

-

**Comment by vraravam** [comment] 2021-05-15 17:32
Please see the [documentation](https://github.com/getferdi/recipes/blob/master/docs/integration.md) regarding creating a recipe for a service that you want to add. The GH repo that you have linked to doesn't have all the important code.

**Comment by vantezzen** [comment] 2021-05-31 14:40
Duplicate of:
getferdi/ferdi#444
getferdi/ferdi#342
getferdi/recipes#387
getferdi/recipes#225
getferdi/recipes#200
getferdi/recipes#185
getferdi/recipes#159
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.

**Closed by vantezzen** 2021-05-31 14:40 UTC
Labels: enhancement, no existing recipe, pending, recipe request
