### ISSUE TITLE
[Recipe Request] SERVICE

### ISSUE THREAD

**Issue by turkishdrillpress** [getferdi/recipes#291] opened 2020-09-19 11:09 UTC
Name of the service Grammarly
URL of the service (e.g. whatsapp.com): grammarly.com/

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- Need to be able to use Grammarly inside some of my services to double-check my spelling and grammar. Having Grammarly work within my services is very important. I don't want to have to cut and paste my work into Grammarly and then cut and paste it again within Ferdi once it has been checked

**Comment by vantezzen** [comment] 2020-09-19 11:24
Duplicate of #284

**Closed by vantezzen** 2020-09-19 11:24 UTC
Labels: recipe request
