### ISSUE TITLE
[Recipe Request] Notion

### ISSUE THREAD

**Issue by YoannBureauP** [getferdi/recipes#300] opened 2020-09-22 12:28 UTC
Name of the service (e.g. WhatsApp): Notion
URL of the service (e.g. whatsapp.com): https://www.notion.so/

Features you want implemented (optional): Notification support

**Comment by Nokia808** [comment] 2020-09-23 16:45
This is already requested at https://github.com/getferdi/recipes/issues/134
So, it is a duplicate of already mentioned request.

@YoannBureauP kindly close this.

**Closed** 2020-09-23 18:43 UTC
Labels: recipe request
