### ISSUE TITLE
Searching contacts gets the notification badge stuck on Facebook Messenger

### ISSUE THREAD

**Issue by HugLifeTiZ** [getferdi/recipes#163] opened 2020-05-09 17:38 UTC
**Describe the bug**
When you search for contacts in Facebook Messenger, the notification badge changes to what appears to be an arbitrary number, and then gets stuck that way. You can't make it go away unless you reload the page.

**To Reproduce**
1. Click the area to search contacts
2. Do a search that will pull up multiple people
3. Notification badge incorrectly appears
4. Press escape to leave search
5. Notification badge stays

**Expected behavior**
The notification badge should not appear at all, or at the very least, should go away when search is exited.

**Screenshots**
I'd prefer not to attach screenshots to protect the privacy of my friends, and because the issue is easily reproducible.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04 via Flatpak
 - Version: 5.5.0

**Comment by mhatvan** [comment] 2021-09-20 06:47
This was fixed in the meantime, cannot reproduce this on v5.6.3-nightly.3

**Closed by mhatvan** 2021-09-20 06:47 UTC
Labels: bug
