### ISSUE TITLE
LINE

### ISSUE THREAD

**Issue by zebrahosting** [getferdi/recipes#785] opened 2021-12-07 08:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Line

### URL of the service

https://line.me/

### GitHub URL to a recipe that has already been created by someone else or you

?

### Features you want implemented

Option to chat would be priority, other options are less important. Line is the most used chat and calling app in Asia

**Comment by vraravam** [comment] 2021-12-07 13:54
@zebrahosting - the way to create a new recipe is well documented. Please create one and submit a PR.

**Comment by kytwb** [comment] 2021-12-27 17:05
Duplicate of:
- #560
- #396
- #296
- #255
- #213
- #212
- #33 
- #28

**Closed by kytwb** 2021-12-27 17:05 UTC
Labels: recipe request :sparkles:
