### ISSUE TITLE
Spike

### ISSUE THREAD

**Issue by phs4-cb1000** [getferdi/recipes#372] opened 2020-11-29 12:38 UTC
Name of the service (e.g. WhatsApp): Spike 
URL of the service (e.g. whatsapp.com): https://spikenow.com/web/

**Comment by mhatvan** [comment] 2021-09-12 09:35
Closing as duplicate of https://github.com/getferdi/recipes/issues/596

**Closed by mhatvan** 2021-09-12 09:35 UTC
Labels: recipe request
